- .github/workflows/release.yml
- .gitignore
- internal/cli/root.go
- add .CHANGELOG.md to gitignore to prevent go-releaser error.
- skip auth validation for version command.
> fix release ci

- README.md
Copying a regular file to /usr/local/bin in macOS is prohibited.
Copying a regular file to /usr/local/bin in macOS require the root privilege.
It's better to let the user choose his way.
> remove copy comand to /usr/local/bin

- internal/cli/cluster/create.go
- internal/cli/cluster/create_test.go
- internal/cli/cluster/delete.go
- internal/cli/cluster/delete_test.go
- internal/cli/cluster/describe.go
- internal/cli/cluster/list.go
- internal/cli/project/list.go
- internal/ui/select_model.go
- Use the select model rather than the input model with project IDs.
- Use "SERVERLESS" rather than "DEVELOPER" when creating clusters.
> Use select model rather than input model with projectIDs

- internal/cli/cluster/cluster.go
- internal/cli/cluster/create.go
- internal/cli/cluster/delete.go
- internal/cli/cluster/describe.go
- internal/cli/cluster/list.go
- internal/cli/config/config.go
- internal/cli/config/create.go
- internal/cli/config/create_test.go
- internal/cli/config/describe.go
- internal/cli/config/edit.go
- internal/cli/config/list.go
- internal/cli/config/list_test.go
- internal/cli/config/set.go
- internal/cli/config/set_test.go
- internal/cli/config/use.go
- internal/cli/project/list.go
- internal/cli/project/project.go
- internal/util/auth.go
- remove period in short description.
- rename `config init` to `config create`
> Text polishing

- internal/cli/cluster/list.go
- internal/cli/config/create.go
- internal/cli/config/use.go
- If the user's terminal has its own background color, using background color may make the text not clear.
> Use foreground color rather than background color

- internal/cli/cluster/create.go
- internal/cli/cluster/create_test.go
- internal/cli/root.go
- internal/cli/update/update.go
- internal/cli/version/version.go
- internal/service/github/version.go
- internal/ui/spinner_model.go
- skip check version after executing 'update'.
- check the version forcibly before updating CLI.
- fix version return wrong the CLI name.
> optimize update process

- README.md
- internal/cli/cluster/create.go
- internal/cli/cluster/create_test.go
- internal/cli/cluster/delete.go
- internal/cli/cluster/delete_test.go
- internal/cli/cluster/describe.go
- internal/cli/cluster/describe_test.go
- internal/cli/cluster/list.go
- internal/cli/cluster/list_test.go
- internal/cli/config/set.go
- internal/cli/config/set_test.go
- internal/cli/project/list.go
- internal/cli/project/list_test.go
- internal/cli/root.go
- internal/helper.go
- internal/prop/property.go
- internal/service/cloud/api_client.go
- internal/util/auth.go
- enable config TiDB Cloud API URL. If not set, use `https://api.tidbcloud.com` as default.
- validate URL when set or using.
> Enable config TiDB Cloud api host

- internal/service/cloud/logic.go
If there is only one project, directly use the one in interactive mode.
> Directly select the only one project

- internal/cli/root.go
- internal/cli/version/version.go
- internal/service/cloud/api_client.go
- Use `RoundTripper` to add `User-Agent` header to HTTP request.
- Fix version message when the version is dev.
> Add user agent http header

- internal/cli/root.go
- internal/cli/update/update.go
- internal/config/config.go
- internal/helper.go
- Use `ticloud` as the CLI name when executing independently.
- Use `cloud` as the CLI name when under TiUP.
> Use different name when under TiUP

- install.sh
We meet the situation when installing ticloud in GitHub action failed because can't download the correct archives from TiUP mirror.
So we change the download site from TiUP mirror to GitHub release.
> Using github release rather than tiup mirror

- internal/cli/update/update.go
- internal/service/github/version.go
Download the latest-version file to get the latest version instead of querying GitHub API.
> Use latest-version file to check for update

- README.md
- internal/cli/config/create.go
`github.com/spf13/viper` uses the dot as the key delimiter, in `ticloud`, the config name is saved as a key. So we should forbid config name with dot unless `ticloud config` can't work properly.
> Forbid config name with dot

- internal/cli/config/config.go
- internal/cli/config/edit.go
- If using `config edit` in the Unix system, open the config file with the vi editor.
- If using `config edit` in Windows, print the config file path instead.
> Fix error when using `config edit` in Windows

- internal/cli/cluster/create.go
- internal/cli/cluster/delete.go
- internal/cli/dataimport/start/local.go
- internal/cli/dataimport/start/start.go
- internal/cli/update/update.go
- Use a buffered channel to avoid channel leak when the receiver exits before the sender, in which case the sender will block.
- Defer ticker. Stop () to close the ticker to lease the ticker channel.
> Fix channel leak

- internal/service/cloud/logic.go
- internal/ui/select_model.go
- Enable pagination and filter on the cluster, project, and import selections.
- Use fmt.Sprintf() to fix panic.
> Enable pagination and filter

- internal/cli/branch/delete.go
- internal/cli/branch/delete_test.go
Optimize branch delete to avoid too many 404
> Optimize branch delete to avoid too many 404

- internal/cli/branch/create.go
- internal/cli/branch/delete.go
- internal/cli/cluster/create.go
- internal/cli/cluster/delete.go
- internal/cli/cluster/delete_test.go
> Optimize create/delete output

- internal/cli/ai/ai.go
- internal/ui/chat_box_model.go
reply's content has links, which is redundant.
- Ask questions without links so that reply's content has no links
> Fix: reply content has links

- internal/cli/serverless/branch/connect.go
- internal/cli/serverless/branch/connectinfo.go
- internal/cli/serverless/branch/describe_test.go
- pkg/tidbcloud/v1beta1/branch/branch.swagger.json
- pkg/tidbcloud/v1beta1/branch/models/branch_endpoints.go
- pkg/tidbcloud/v1beta1/branch/models/private_g_c_p.go
> Update branch swagger

- internal/cli/auth/auth.go
- internal/cli/auth/logout.go
- internal/cli/serverless/export/create.go
- internal/cli/serverless/export/download.go
> Fix export typo

- internal/cli/auth/login.go
- internal/cli/serverless/backup/backup.go
- internal/cli/serverless/backup/delete.go
- internal/cli/serverless/backup/describe.go
- internal/cli/serverless/backup/list.go
- internal/cli/serverless/branch/branch.go
- internal/cli/serverless/create.go
- internal/cli/serverless/dataimport/import.go
- internal/cli/serverless/dataimport/start/start.go
- internal/cli/serverless/delete.go
- internal/cli/serverless/describe.go
- internal/cli/serverless/export/cancel.go
- internal/cli/serverless/export/create.go
- internal/cli/serverless/export/describe.go
- internal/cli/serverless/export/download.go
- internal/cli/serverless/export/export.go
- internal/cli/serverless/export/list.go
- internal/cli/serverless/list.go
- internal/cli/serverless/region.go
- internal/cli/serverless/restore.go
- internal/cli/serverless/shell.go
- internal/cli/serverless/spending_limit.go
- internal/cli/serverless/update.go
> Polish help message

- internal/cli/config/create.go
- internal/cli/serverless/branch/create.go
- internal/cli/serverless/create.go
- internal/cli/serverless/dataimport/start/start.go
- internal/cli/serverless/spending_limit.go
- internal/cli/serverless/update.go
- internal/cli/upgrade/upgrade.go
- internal/service/cloud/logic.go
> Replace deprecated use

- internal/cli/serverless/dataimport/start/start.go
- internal/cli/serverless/export/create.go
- internal/service/cloud/logic.go
- internal/ui/select_model.go
> Fix select ui npe

- internal/util/download.go
> Remove url when export download error

- internal/cli/serverless/sqluser/create.go
- internal/cli/serverless/sqluser/create_test.go
> set AutoPrefix to true when creating a sql user

- go.mod
- go.sum
- internal/cli/serverless/update.go
> serverless update, mark flags at least one

- .github/workflows/release.yml
- internal/cli/version/version.go
- internal/version/version.go
> add nightly release

- .github/workflows/release.yml
- internal/cli/version/version.go
> update nightly version info

- .github/workflows/release.yml
- internal/cli/version/version.go
> disable release when version is nightly 

- internal/cli/version/version.go
> update nighly version format

- internal/config/store/keyring.go
> Polish error hint

- docs/generate_doc/ticloud_auth.md
- docs/generate_doc/ticloud_auth_whoami.md
- docs/generate_doc/ticloud_serverless_create.md
- docs/generate_doc/ticloud_serverless_update.md
- internal/cli/auth/auth.go
- internal/cli/auth/whoami.go
> add whoami

- internal/cli/auth/auth.go
- internal/cli/auth/whoami.go
> add org name in whoami

- internal/cli/serverless/export/create.go
> Fix export fail with default compression value and default filetype

- docs/generate_doc/ticloud_serverless_create.md
- docs/generate_doc/ticloud_serverless_export_create.md
- docs/generate_doc/ticloud_serverless_import_start.md
- internal/cli/serverless/create.go
- internal/cli/serverless/export/create.go
- internal/cli/serverless/export/ui.go
- internal/cli/serverless/update.go
- internal/service/cloud/api_client.go
- pkg/tidbcloud/v1beta1/serverless/export.swagger.json
- pkg/tidbcloud/v1beta1/serverless/export/api/openapi.yaml
- pkg/tidbcloud/v1beta1/serverless/export/api_export_service.go
- pkg/tidbcloud/v1beta1/serverless/export/model_export_service_download_export_files_body.go
> Export command fix
